/** WebP variants of a product image generated by the API (longest side in px), plus the original URL. */
export type ImageVariants = Partial<Record<"64" | "256" | "512" | "1024" | "original", string>>;

const SIZES = ["64", "256", "512", "1024"] as const;

/**
 * Smallest API variant whose longest side is at least `minPx`, falling back to the original image when the
 * API sent no variants. The result still goes through next/image; the variant only gives the optimizer a
 * small, fast source instead of the full-size original on the slow ERP host.
 */
export function imageVariant(original: string | null | undefined, variants: ImageVariants | null | undefined, minPx: number): string | null {
  if (!original) return null;
  if (!variants) return original;
  return SIZES.map((size) => (Number(size) >= minPx ? variants[size] : undefined)).find(Boolean) ?? variants["1024"] ?? original;
}
